### ISSUE TITLE
Problem on creating attribute k12005

### ISSUE THREAD

**Issue by MonicaMina** [ZEISS-PiWeb/PiWeb-Api#91] opened 2021-04-30 06:38 UTC
Hello, I have a problem on creating a new part that contains the "/" character.
I know this character is used to separate the various folders in a path. Is there a way to avoid that the "/" character is interpreted as the separator for a new folder?
For example, I would like to create the path "CCCC 11/3 SS/operation20/test", where the parts to create are three:
"CCCC 11/3 SS",
"operation20",
"test",
but I got an error when I try to create this one "CCCC 11/3 SS" (that contians the "/" char)

Thanks in advance

**Comment by czthiele** [comment] 2021-04-30 08:16
Hello @MonicaMina,
this question is a duplicate of #80 (which was asked by you). It is already answered and it would be great to know if the solution solved your problem.

**Closed** 2021-04-30 08:17 UTC
Labels: duplicate, question
