### ISSUE TITLE
Build failed - NETSDK1045

### ISSUE THREAD

**Issue by ThomasFischer1** [ZEISS-PiWeb/PiWeb-Api#20] opened 2020-02-19 09:23 UTC
**Affected Version(s)**
Commit 172ec88b, developer branch

**Describe the bug**
Can't build.
"Error NETSDK1045: Das aktuelle .NET SDK unterstützt .NET Core 3.0 nicht als Ziel. Geben Sie entweder .NET Core 2.1 oder niedriger als Ziel an, oder verwenden Sie eine .NET SDK-Version, die .NET Core 3.0 unterstützt. (1, 1)"

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
Newest SDK is installed - v3.1.102.
Use VS 2017.

**Comment by czthiele** [comment] 2020-02-19 10:50
Hello,
the problem is VisualStudio 2017, which includes MSBuild Version 15.X. 
For .NET Core 3.X however the required version is VS2019, and MSBuild 16.X, see Microsofts [announcement](https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0/) under *What you should know about 3.0*: 
```Visual Studio 2019 16.3 is a required update for Visual Studio users on Windows that want to use .NET Core 3.0.```

So if you want to build the API yourself, you need VS2019. The easier way would be to use our [NuGet](https://www.nuget.org/packages/Zeiss.IMT.PiWebApi.Client/). Please note that latest released version 5.0.1 doesnt support .NET Core yet. This compatibility will be released with API 6.0.0.

**Closed** 2020-02-20 11:38 UTC
Labels: bug
